version: "3.8"  # Usamos una versión más reciente para compatibilidad con healthchecks

services:
  angular-app:
    build:
      context: ./Angular/Videogames-TFG-Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - spring-boot-app
    environment:
      - NODE_ENV=development
    volumes:
      - ./Angular/Videogames-TFG-Frontend/src/assets/games:/app/src/assets/games

  spring-boot-app:
    build:
      context: ./Springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - videogames-tfg-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  videogames-tfg-mysql-data: