use videogames;

INSERT INTO videojuegos (id, nombre, genero, descripcion, anio_Publicacion, precio, calificacion_por_edades, publicador, image_Path) VALUES
(1, 'Elden Ring', 'Action RPG', 'A fantasy action RPG.', 2022, 59.99, 'Mature', 'FromSoftware', '../../../../../assets/games/elden_ring.jpeg'),
(2, 'Diablo IV', 'Action RPG', 'An action RPG.', 2023, 34.99, 'Mature', 'Blizzard Entertainment', '../../../../../assets/games/diablo.jpg'),
(3, 'DOTA 2', 'MOBA', 'A multiplayer online battle arena game.', 2013, 0, 'Teen', 'Valve Corporation', '../../../../../assets/games/dota2.jpg'),
(4, 'The Witcher 3: Wild Hunt', 'Action RPG', 'An open-world action RPG.', 2015, 29.99, 'Mature', 'CD Projekt', '../../../../../assets/games/The-Witcher-3-Wild-Hunt.jpg'),
(5, 'Cyberpunk 2077', 'Open-world RPG', 'A futuristic open-world RPG.', 2020, 49.99, 'Mature', 'CD Projekt', '../../../../../assets/games/cyberpunk.jpg'),
(6, 'Hades', 'Roguelike', 'A roguelike dungeon crawler.', 2020, 24.99, 'Teen', 'Supergiant Games', '../../../../../assets/games/hades.png'),
(7, 'Among Us', 'Social Deduction', 'A multiplayer social deduction game.', 2018, 4.99, 'Everyone 10+', 'Innersloth', '../../../../../assets/games/among_us.jpeg'),
(8, 'Assassin\'s Creed Valhalla', 'Action-Adventure', 'An open-world action-adventure game.', 2020, 59.99, 'Mature', 'Ubisoft', '../../../../../assets/games/ac_valhalla.jpg'),
(9, 'Minecraft', 'Sandbox', 'A sandbox game.', 2011, 26.95, 'Everyone 10+', 'Mojang Studios', '../../../../../assets/games/minecraft.jpg'),
(10, 'Fortnite', 'Battle Royale', 'A battle royale game.', 2017, 0, 'Teen', 'Epic Games', '../../../../../assets/games/fortnite.jpg'),
(11, 'League of Legends', 'MOBA', 'A multiplayer online battle arena game.', 2009, 0, 'Teen', 'Riot Games', '../../../../../assets/games/league_of_legends.jpg'),
(12, 'Valorant', 'First-person Shooter', 'A tactical first-person shooter.', 2020, 0, 'Teen', 'Riot Games', '../../../../../assets/games/valorant.jpg'),
(13, 'Final Fantasy VII Remake', 'RPG', 'A remake of the classic RPG.', 2020, 59.99, '16+', 'Square Enix', '../../../../../assets/games/ffvii_remake.jpg'),
(14, 'God of War', 'Action-adventure', 'An action-adventure game based on mythology.', 2018, 39.99, '18+', 'Sony Interactive Entertainment', '../../../../../assets/games/gow.jpg'),
(15, 'Ratchet and Clank', 'Action-platformer', 'An action-platformer game.', 2016, 29.99, '10+', 'Sony Interactive Entertainment', '../../../../../assets/games/ratchet_and_clank.jpg'),
(16, 'The Legend of Zelda: Breath of the Wild', 'Action-adventure', 'An open-world action-adventure game.', 2017, 59.99, '12+', 'Nintendo', '../../../../../assets/games/BOTW.jpg'),
(17, 'Super Mario Odyssey', 'Platform', 'A platform game.', 2017, 49.99, '7+', 'Nintendo', '../../../../../assets/games/super_mario_odyssey.jpg'),
(18, 'Red Dead Redemption 2', 'Action-adventure', 'An open-world action-adventure game set in the Wild West.', 2018, 59.99, '18+', 'Rockstar Games', '../../../../../assets/games/rdr2.jpg'),
(19, 'Splatoon 3', 'Third-person shooter', 'A colorful and fast-paced multiplayer shooter.', 2022, 59.99, '10+', 'Nintendo', '../../../../../assets/games/splatoon_3.jpg'),
(20, 'Animal Crossing: New Horizons', 'Simulation', 'A social simulation game where you build and manage your island.', 2020, 59.99, '3+', 'Nintendo', '../../../../../assets/games/animal_crossing.jpg'),
(21, 'Mario Kart 8 Deluxe', 'Racing', 'A kart racing game with various characters and tracks.', 2017, 59.99, '3+', 'Nintendo', '../../../../../assets/games/mario_kart_8.jpg'),
(22, 'Hollow Knight', 'Metroidvania', 'An action-adventure game with exploration and platforming elements.', 2017, 14.99, '10+', 'Team Cherry', '../../../../../assets/games/hollow_knight.jpg'),
(23, 'Stardew Valley', 'Simulation', 'A farming simulation game with RPG elements.', 2016, 14.99, '7+', 'ConcernedApe', '../../../../../assets/games/stardew_valley.jpg'),
(24, 'Sekiro: Shadows Die Twice', 'Action-adventure', 'A challenging action-adventure game set in a fictional Japan.', 2019, 59.99, '18+', 'Activision', '../../../../../assets/games/sekiro.jpg'),
(25, 'Celeste', 'Platformer', 'A challenging platformer game with a touching story.', 2018, 19.99, '10+', 'Matt Makes Games', '../../../../../assets/games/celeste.jpg'),
(26, 'Horizon Zero Dawn', 'Action RPG', 'An open-world action RPG set in a post-apocalyptic world.', 2017, 49.99, '16+', 'Sony Interactive Entertainment', '../../../../../assets/games/horizon_zero_dawn.jpg'),
(27, 'Persona 5', 'RPG', 'A role-playing game where you live a double life as a high school student and a phantom thief.', 2016, 59.99, '16+', 'Atlus', '../../../../../assets/games/persona_5.jpg');